name: main
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          dotnet build -c Release
          dotnet pack -c Release --include-symbols --include-source
      - name: Test
        run: |
          dotnet test -c Release
      - uses: actions/upload-artifact@v3
        with:
          path: |
            Sdcb.ScreenCapture/bin/Release/*.nupkg
            Sdcb.ScreenCapture/bin/Release/*.snupkg
          if-no-files-found: error
      - name: Publish to NuGet
        if: github.event_name == 'push'
        run: dotnet nuget push ./Sdcb.ScreenCapture/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}} --skip-duplicate